#ifndef text_h
#define text_h
// space, in text will be written as m
//||, in text will be written as q
// -, in text will be written as v
/*TOC:
 * 0. off
 * 1. asleep animation
 * 2. awake animation
 * 3. instructions
 * 4. oracle intro
 * 5. fortune prompt is your conscience clean yes 1 no 2
 * 6. fortune response
 * 7. wish prompt what do you wish for affection 1 riches 2 fame 3 health 4
 * 8. wish response
 * 9-12. wish values, in order, affection, riches, fame, health
 * 13-22. good fortunes
 * 23-32. bad fortunes
 */
char* text[]=
{"MMMMMM"
 "QQVVQQ",
 "QQ88QQ",
 "PRESSMLEFTMBUTTONMASMNEEDEDMBASEDMONMINDICATORM",
 "THEMORACLEMHASMRISENMVMSEEMYOURMFATEMV1MPLEADYOURDESIRESMV2MPUTORACLETOSLEEPMV3",
 "ISMYOURMCONSCIENCEMCLEANMYESMV1MNOMV2",
 "QQTHEMEYEMSEESMALLQQ",
 "THEREMAREMDESIRESMIMCANMFULFILLMCHOOSEMONEMVMAFFECTIONV1MRICHESV2MHEALTHV3MSUCCESSV4"
 "YOURMPLEASMAREMHEARDMQQQQQQ"
 "OPENMYOURMHEARTMTOMTHOSEMAROUNDMYOUMANDMFINDMTHATMYOUMSEEK",
 "SORRYMIMDONTMPOSSESSMRICHESMHAHA",
 "FINDMAMDOCTORMSOMHEALTHMCANMFINDMYOU",
 "PERHAPSMOPENMAMSOCIALMNETWORKMACCOUNTMHAHA"
 "LIFEMSHALLMREPAYMYOURMSELFLESSMDEEDS",
 "YOURMFOODMSHALLMTASTEMTASTIERMTODAY",
 "STARSMSHALLMLINEMYOURMPATH",
 "YOURMOPSMSHALLMNOTMSUCCEED",
 "THEMSTARSMSEEMTOMYOURMPROSPERITY",
 "NICEMHAIRCUTSMLIEMAHEAD",
 "THEMRAINMSHALLMREFRESHMYOURMDAYMSOON",
 "BOTHMSIDESMOFMYOURMHEADMCUSHIONMSHALLMBEMCOLD",
 "AMFRIENDMSHALLMHANDMYOUMAMDOLLARMUPONMSEEINMTHISMFORTUNE",
 "YOURMPREFERREDMTUNESMSHALLMPLAYMSOON"
 "YOURMDESIRESMSHALLMBESTMYOU",
 "YOURMFALLMISMIMMINENT",
 "YOURMOPSMSHALLMENJOYMTODAY",
 "TOURMFOODMSHALLMTASTEMLESSMTASTYMTODAY",
 "YOURMLEASTMPREFERREDMTUNESMSHALLMPLAYMSOON",
 "TERRIBLEMHAIRCUTSMLIEMAHEAD",
 "BOTHMSIDESMOFMYOURMHEADMCUSHIONMSHALLMBEMHOT",
 "AMHOTMSADMDAYMLIESMAHEAD",
 "NOMFUNMLIESMAHEAD"
 "YOURMSLEEPMSHALMNOTMBEMRESTFULMTONITE"
 };
/*
char* goodfortunes[10] =
{"LIFEMSHALLMREPAYMYOURMSELFLESSMDEEDS",
 "YOURMFOODMSHALLMTASTEMTASTIERMTODAY",
 "STARSMSHALLMLINEMYOURMPATH",
 "YOURMOPSMSHALLMNOTMSUCCEED",
 "THEMSTARSMSEEMTOMYOURMPROSPERITY",
 "NICEMHAIRCUTSMLIEMAHEAD",
 "THEMRAINMSHALLMREFRESHMYOURMDAYMSOON",
 "BOTHMSIDESMOFMYOURMHEADMCUSHIONMSHALLMBEMCOLD",
 "AMFRIENDMSHALLMHANDMYOUMAMDOLLARMUPONMSEEINMTHISMFORTUNE",
 "YOURMPREFERREDMTUNESMSHALLMPLAYMSOON"
 };
char* badfortunes[10] =
{"YOURMDESIRESMSHALLMBESTMYOU",
 "YOURMFALLMISMIMMINENT",
 "YOURMOPSMSHALLMENJOYMTODAY",
 "TOURMFOODMSHALLMTASTEMLESSMTASTYMTODAY",
 "YOURMLEASTMPREFERREDMTUNESMSHALLMPLAYMSOON",
 "TERRIBLEMHAIRCUTSMLIEMAHEAD",
 "BOTHMSIDESMOFMYOURMHEADMCUSHIONMSHALLMBEMHOT",
 "AMHOTMSADMDAYMLIESMAHEAD",
 "NOMFUNMLIESMAHEAD"
 "YOURMSLEEPMSHALMNOTMBEMRESTFULMTONITE"
 };
asleep = "QQVVQQ"
awake = "QQ88QQ"
instructions = "PRESSMLEFTMBUTTONMASMNEEDEDMBASEDMONMINDICATORM"
awake_txt  = "THEMORACLEMHASMRISENMVMSEEMYOURMFATEMV1MPLEADYOURDESIRESMV2MPUTORACLETOSLEEPMV3"
fortune_prompt = "ISMYOURMCONSCIENCEMCLEAN"
fortune_response = "QQTHEMEYEMSEESMALLQQ"
wish_prompt = "THEREMAREMDESIRESMIMCANMFULFILLMCHOOSEMONEMVMAFFECTIONV1MRICHESV2MHEALTHV3MSUCCESSV4"
wish_response = "YOURMPLEASMAREMHEARDMQQQQQQ"
char* wishes[4]=
{"OPENMYOURMHEARTMTOMTHOSEMAROUNDMYOUMANDMFINDMTHATMYOUMSEEK",
 "SORRYMIMDONTMPOSSESSMRICHESMHAHA",
 "FINDMAMDOCTORMSOMHEALTHMCANMFINDMYOU",
 "PERHAPSMOPENMAMSOCIALMNETWORKMACCOUNTMHAHA"
};
*/
#endif
